volumes:
  influxdb-data:

version: "3"
services:
  # DATABASE
  influxdb:
    image: "influxdb:latest"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${GF_SECRET}
    volumes:
      - influxdb-data:/var/lib/influxdb
  chronograf:
    image: "chronograf:latest"
    entrypoint: "chronograf --influxdb-url=http://influxdb:8086"
    depends_on:
      - influxdb

  # DASHBOARD
  grafana:
    image: "chachakawooka/webperf_grafana"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECRET}
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
    depends_on:
      - influxdb
    labels:
      - "traefik.http.services.webperf.loadbalancer.server.port=3000"
      - "traefik.http.routers.webperf.rule=PathPrefix(`/webperf/${NAME}`)"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.middlewares.webperf-stripprefix.stripprefix.prefixes=/webperf/${NAME}"
      - "traefik.http.routers.webperf.middlewares=webperf-stripprefix@docker"

  # lighthouse
  webperf-dashboard-lighthouse:
    image: "chachakawooka/webperf_lighthouse"
    environment:
      - HOST=influxdb
      - URLS=${URLS}
      - CRON=${CRON}
    depends_on:
      - influxdb

networks:
  proxy:
    external: true