volumes:
  influxdb-data:
  grafana-data:

version: "3"
services:
  # DATABASE
  influxdb:
    image: "influxdb:latest"
    networks:
      - webperfnet 
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${GF_SECRET}
    volumes:
      - influxdb-data:/var/lib/influxdb
  chronograf:
    image: "chronograf:latest"
    networks:
      - webperfnet 
    entrypoint: "chronograf --influxdb-url=http://influxdb:8086"
    depends_on:
      - influxdb

  # DASHBOARD
  grafana:
    image: "chachakawooka/webperf_grafana"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECRET}
    depends_on:
      - influxdb
    networks:
      - proxy
      - webperfnet
    volumes:
      - grafana-data:/var/lib/grafana
    deploy:
      labels:
        - "traefik.http.services.webperf${NAME}.loadbalancer.server.port=3000"
        - "traefik.http.routers.webperf${NAME}.rule=HOST(`${DOMAIN}`)"
        - "traefik.enable=true"
        - "traefik.http.routers.webperf${NAME}.entrypoints=web"
        - "traefik.docker.network=proxy"
    links:
      - influxdb

  # lighthouse
  webperf-dashboard-lighthouse:
    image: "chachakawooka/webperf_lighthouse"
    networks:
      - proxy
      - webperfnet 
    environment:
      - HOST=influxdb
      - URLS=${URLS}
      - CRON=${CRON}
    depends_on:
      - influxdb
    deploy:
      labels:
        - "traefik.http.services.webperfl${NAME}.loadbalancer.server.port=3000"
        - "traefik.http.routers.webperfl${NAME}.rule=HOST(`${DOMAIN}`) && PathPrefix(`/viewer`)"
        - "traefik.enable=true"
        - "traefik.http.routers.webperfl${NAME}.entrypoints=web"
        - "traefik.docker.network=proxy"
        - "traefik.http.middlewares.webperfl${NAME}-stripprefix.stripprefix.prefixes=/viewer"
        - "traefik.http.routers.webperfl${NAME}.middlewares=webperfl${NAME}-stripprefix@docker"
networks:
  webperfnet:
  proxy:
    external: true