volumes:
  influxdb-data:

version: "3"
services:
  # DATABASE
  influxdb:
    image: "influxdb:latest"
    networks:
      - webperfnet 
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${GF_SECRET}
    volumes:
      - influxdb-data:/var/lib/influxdb
  chronograf:
    image: "chronograf:latest"
    entrypoint: "chronograf --influxdb-url=http://influxdb:8086"
    depends_on:
      - influxdb

  # DASHBOARD
  grafana:
    image: "chachakawooka/webperf_grafana"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECRET}
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_SERVER_SERVER_FROM_SUB_PATH=${GF_SERVER_SERVER_FROM_SUB_PATH}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    depends_on:
      - influxdb
    networks:
      - proxy
      - webperfnet
    deploy:
      labels:
        - "traefik.http.services.webperf${NAME}.loadbalancer.server.port=3000"
        - "traefik.http.routers.webperf${NAME}.rule=PathPrefix(`/webperf/${NAME}`)"
        - "traefik.enable=true"
        - "traefik.http.routers.webperf${NAME}.entrypoints=web"
        - "traefik.docker.network=proxy"
        - "traefik.http.middlewares.webperf${NAME}-stripprefix.stripprefix.prefixes=/webperf/${NAME}"
        - "traefik.http.routers.webperf${NAME}.middlewares=webperf${NAME}-stripprefix@docker"
    links:
      - influxdb

  # lighthouse
  webperf-dashboard-lighthouse:
    image: "chachakawooka/webperf_lighthouse"
    networks:
      - webperfnet 
    environment:
      - HOST=influxdb
      - URLS=${URLS}
      - CRON=${CRON}
    depends_on:
      - influxdb

networks:
  webperfnet:
  proxy:
    external: true