name: Publish Lighthouse Tag
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch
    steps:

    - name: Copy Repo Files
      uses: actions/checkout@master
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: 'lighthouse'
        TAG: ${{ steps.vars.outputs.tag }}
        DOCKERFILE_PATH: 'packages/lighthouse/Dockerfile'
        BUILD_CONTEXT: 'packages/lighthouse/'
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
