name: Publish Lighthouse Latest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch
    steps:

    - name: Copy Repo Files
      uses: actions/checkout@master

    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: 'lighthouse'
        TAG: 'latest'
        DOCKERFILE_PATH: 'packages/lighthouse/Dockerfile'
        BUILD_CONTEXT: 'packages/lighthouse/'
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
